version: "3"
services:
  sip-pdb:
    build: .
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./instance
        target: /app/instance
      - type: bind
        source: ./migrations
        target: /app/migrations
    restart: unless-stopped